version: "3.8"

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: ${APP_NAME}_mariadb
    restart: always
    env_file:
      - ".env"
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - "./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
      - "./docker/data:/docker-entrypoint-initdb.d"

  adminer:
    image: adminer:latest
    container_name: ${APP_NAME}_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080